#! /bin/bash

if [ -z "$1" ];  then
    echo "Pass profile name as an argument"
    exit 1
fi

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

AWS_DEFAULT_PROFILE=$1 PS1="\[${green}\]SOK AWS BASH [\[${red}\]$AWS_DEFAULT_PROFILE\[${green}\]]:\[${reset}\] " bash
