#! /bin/bash

PROFILES=($(cat ~/.aws/config | grep '\[profile' | sed -n 's/\[profile \(.*\).*\]/\1/p'))

if [ -z "$1" ];  then
    echo "Pass profile name as an argument. Mayhaps one of these?"
    echo
    printf '%s\n' "${PROFILES[@]}"
    exit 1
fi

if [[ ! " ${PROFILES[@]} " =~ " ${1} " ]]; then
    # whatever you want to do when arr doesn't contain value
    echo "Cowardly refusing to open AWS SHELL for profile $1"
    echo "No such profile in ~/.aws/profile"
    exit 1
fi

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

AWS_DEFAULT_PROFILE=$1 PS1="\[${green}\]AWS [\[${red}\]$AWS_DEFAULT_PROFILE\[${green}\]]:\[${reset}\] \w $ " bash
